const data = {
  products: [
    {
      name: 'Oversized T',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInScout: 20,
      discription: 'A popular shirt',
    },
    {
      name: 'Fit T',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 100,
      brand: 'Adidas',
      rating: 4.3,
      numReviews: 12,
      countInScout: 35,
      discription: 'A cool shirt',
    },
    {
      name: 'Slim T',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 100,
      brand: 'Raymond',
      rating: 4.3,
      numReviews: 12,
      countInScout: 35,
      discription: 'A cool shirt',
    },
    {
      name: 'Slim T ',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 100,
      brand: 'Raymond',
      rating: 4.3,
      numReviews: 12,
      countInScout: 35,
      discription: 'A cool shirt',
    },
  ],
};
